#
#Mon Jul 13 16:52:32 COT 2026
goog\:chromeOptions={args\=[--start-maximized, --disable-popup-blocking, --disable-notifications, remote-allow-origins\=*], extensions\=[]}
acceptInsecureCerts=false
browserName=chrome
